# Generated by Django 5.2.4 on 2025-08-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.CharField(blank=True, default='Working', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='inventory.department'),
        ),
    ]
