# Generated by Django 5.2.4 on 2025-08-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_component_serial_number_alter_component_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.department'),
        ),
    ]
